# -*- coding: utf-8 -*-
"""HeartDiseaseDatasetOverview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igE9RJdMqnTuIsVi_NXZ6mgK41ME-Vce
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("heart.csv")

data.head()

data.tail()

data.info()

data.shape

data.describe()

data.columns

data.dtypes